runner:
  golint:
    cmd: golint ./...
    format: golint
  govet:
    cmd: go vet ./...
    format: govet
  misspell:
    cmd: misspell $(git ls-files | grep -v -e go.mod -e go.sum)
    errorformat:
      - "%f:%l:%c: %m"
  unparam:
    cmd: unparam ./...
    errorformat:
      - "%f:%l:%c: %m"
  revive:
    cmd: revive -config=.revive.toml ./...
    format: golint
  golangci:
    cmd: golangci-lint run --out-format=line-number ./...
    errorformat:
      - '%E%f:%l:%c: %m'
      - '%E%f:%l: %m'
      - '%C%.%#'
