# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  lint:
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}

    docker:
      - image: circleci/golang:1.12
        environment:
          GO111MODULE: "on"
          REVIEWDOG_VERSION: 0.9.11
    steps:
      - checkout
      - run: 'curl -fSL https://github.com/reviewdog/reviewdog/releases/download/$REVIEWDOG_VERSION/reviewdog_linux_amd64 -o reviewdog && chmod +x ./reviewdog'
      - run: 'go get golang.org/x/lint/golint github.com/client9/misspell/cmd/misspell mvdan.cc/unparam'
      - run: './reviewdog -conf=./.reviewdog.yml -reporter=github-pr-check'

  test:
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}

    docker:
      - image: circleci/golang:1.12
        environment:
          GO111MODULE: "on"

    steps:
      - checkout

      - restore_cache:
          name: Restore go modules cache
          keys:
              - v1-mod-{{ .Branch }}-{{ checksum "go.mod" }}

      - run:
          name: Vendoring
          command: go mod download


      - run: 'go test -v ./...'

      - save_cache:
          name: Save go modules cache
          key: v1-mod-{{ .Branch }}-{{ checksum "go.mod" }}
          paths:
              - ~/go/pkg/mod/cache

  release:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: curl -sL https://git.io/goreleaser | bash

workflows:
  version: 2
  build:
    jobs:
      - lint
      - test
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
