# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}

    docker:
      - image: circleci/golang:1.12
        environment:
          GO111MODULE: "on"

    steps:
      - checkout

      - restore_cache:
          name: Restore go modules cache
          keys:
              - v1-mod-{{ .Branch }}-{{ checksum "go.mod" }}

      - run:
          name: Vendoring
          command: go mod download


      - run:
          name: Test
          command: |
              go test -v ./...

      - save_cache:
          name: Save go modules cache
          key: v1-mod-{{ .Branch }}-{{ checksum "go.mod" }}
          paths:
              - ~/go/pkg/mod/cache

  release:
    docker:
      - image: circleci/golang:1.10
    steps:
      - checkout
      - run: curl -sL https://git.io/goreleaser | bash

workflows:
  version: 2
  build:
    jobs:
      - build
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
